
##############################################################
# Terminal Tools Configuration for "Terminal Tools Demo"
# Add environments under "Evnironments"
# Adjust the menu under "Menu" to your needs
##############################################################
Projectname: "Terminal Tools Demo"
Environments:
  Live:
    #required
    Host: ""
    Sshuser: ""
    Repodir: ""
    #additional settings
    Domain: ""
    Sshport: ""
    Composerpath: ""
    PhpPath: ""
  Dev:
    #add dev site info here
Menu:
  Heading1:
    Title: Local
    Item1:
      Title: Local "deploy" (git pull etc.)
      Command: "ttools/githelpers/lib/git-pull.sh ttools/silverstripe/lib/deploy.sh"
    Item2:
      Title: Wipe cache
      Command: "ttools/silverstripe/lib/wipe-cache.sh"
    Item3:
      Title: Overwrite Local Site with Database & Assets from Live Site
      Command: "ttools/sitesync-core/local/sync-environments.sh Live Local"
  Heading2:
    Title: Dev Site
    Item1:
      Title: SSH Dev Site
      Command: "ttools/core/local/ssh.sh Dev"
    Item2:
      Title: Deploy Dev Site
      Command: "ttools/githelpers/local/git-pull-remote.sh Dev ttools/silverstripe/lib/deploy.sh"
    Item3:
      Title: Push Database & Assets to Dev Site
      Command: "ttools/sitesync-core/local/sync-environments.sh Local Dev"
    Item4:
      Title: Overwrite Dev Site with Database & Assets from Live Site
      Command: "ttools/sitesync-core/local/sync-environments.sh Live Dev"      
  Heading3:
    Title: Live Site
    Item1:
      Title: SSH Live Site
      Command: "ttools/core/local/ssh.sh Live"
    Item2:
      Title: Deploy Live Site
      Command: "ttools/githelpers/local/git-pull-remote.sh Live ttools/silverstripe/lib/deploy.sh"
Sitesync:
  FrameworkModule: 'ttools/sitesync-silverstripe'


